/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package uno;

import com.sun.awt.AWTUtilities;
import java.awt.Image;

import javax.swing.ImageIcon;

/**
 *
 * @author David
 */
public class bienvenido extends javax.swing.JFrame {
    LogIn l ;
    MenuPrincipal taquilla;
    MenuDulceria dulceria;
    boolean vandera = false;
    ImageIcon imagen ;
    ImageIcon imagen1 ;
    
    /**
     * Creates new form bienvenido
     */
    public bienvenido() {
        initComponents();
        //jPanel1.setVisible(false);
        jButton1.setVisible(false);
            jButton2.setVisible(false);
         taquilla= new MenuPrincipal();
         dulceria = new MenuDulceria();
         imagen = new ImageIcon(getClass().getResource(("fondo.jpg")));
          fondo.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(fondo.getWidth(), fondo.getHeight(), Image.SCALE_DEFAULT)));
          //jPanel1.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(fondo.getWidth(), fondo.getHeight(), Image.SCALE_DEFAULT)));
        imagen1 = new ImageIcon(getClass().getResource(("nada.png")));
          fondo1.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(fondo1.getWidth(), fondo1.getHeight(), Image.SCALE_DEFAULT)));
          
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fondo1 = new javax.swing.JLabel();
        Sesion = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(490, 370));
        setMinimumSize(new java.awt.Dimension(490, 370));
        setPreferredSize(new java.awt.Dimension(490, 370));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(480, 230));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(null);

        jButton1.setText("Dulceria");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 11, 88, 58);

        jButton2.setText("taquella");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(368, 14, 84, 52);
        jPanel1.add(fondo1);
        fondo1.setBounds(4, 4, 480, 230);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 480, 230);

        Sesion.setText("Usuario");
        Sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SesionActionPerformed(evt);
            }
        });
        getContentPane().add(Sesion);
        Sesion.setBounds(360, 300, 69, 23);
        getContentPane().add(fondo);
        fondo.setBounds(0, -6, 490, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SesionActionPerformed
        // TODO add your handling code here:
        l = new LogIn();
        l.setVisible(true);
        
        if(vandera =l.valido1())
        {
            System.out.println("verdadero");
            jButton1.setVisible(true);
            jButton2.setVisible(true);
        }
        else
        {
         jButton1.setVisible(false);
            jButton2.setVisible(false);   
        }
    }//GEN-LAST:event_SesionActionPerformed

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
       try{
        if(vandera =l.valido1())
        {
            System.out.println("verdadero");
            jButton1.setVisible(true);
            jButton2.setVisible(true);
        }
        else
        {
         jButton1.setVisible(false);
            jButton2.setVisible(false);   
        }
       }catch(Exception e){
           
       }
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        taquilla.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dulceria.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bienvenido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sesion;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
